# Generated by Django 4.2.16 on 2024-10-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MyExpense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Category", models.CharField(max_length=100)),
                ("Amount", models.CharField(max_length=100)),
                ("Comments", models.CharField(max_length=100)),
                ("Created_At", models.DateTimeField(auto_now=True)),
                ("Updated_At", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
